fix(responsive ui): fix issue ui display incorrectly on ipad or tablet
lemonadesocial/lemonade-flutter pull request #105
Opened 2023-09-05 06:32 UTC by roncoderpush

## Overview
- Fix issue ui display incorrectly on ipad or tablet devices

## Screenshots
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-05 at 13 22 04](https://github.com/lemonadesocial/lemonade-flutter/assets/108661349/26dce717-bc75-4e2f-8cf6-43827d4a6ffc)

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-05 at 13 22 59](https://github.com/lemonadesocial/lemonade-flutter/assets/108661349/100021c5-1339-4635-a1f5-f2970c287db9)

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-05 at 13 23 11](https://github.com/lemonadesocial/lemonade-flutter/assets/108661349/7c5b533e-f326-4368-bc09-335045b70f37)

2023-09-05 11:17 UTC, sieuhuflit requested changes
Remove this _limitAppLayoutBuilder due to unused.

2023-09-06 03:56 UTC, sieuhuflit approved these changes
LGTM 💯

2023-09-06 04:05 UTC, RonTran636 commented
@sieuhuflit lints fixed, please review again

2023-09-06 04:51 UTC, sieuhuflit approved these changes

2023-09-06 04:51 UTC, merged