feat(poap): implement transfer modification subscription and transfer poap
lemonadesocial/lemonade-flutter pull request #130
Opened 2023-09-14 08:15 UTC by mthinh

# What ?
- implement transfer modification subscription
- implement transfer poap

# Screenshot 

https://github.com/lemonadesocial/lemonade-flutter/assets/28992487/cdf1b244-2e5a-4db8-877d-8b7d389483e5

2023-09-14 10:01 UTC, roncoderpush requested changes
Overall looking good

2023-09-15 07:13 UTC, sieuhuflit reviewed
Leaving some comment

2023-09-15 07:13 UTC, sieuhuflit commented on lib/core/presentation/widgets/poap/poap_transfer_success_poup/poap_transfer_success_popup.dart
> +                            color: const Color.fromRGBO(32, 41, 38, 1),
Should define in Colors file

2023-09-15 08:26 UTC, mthinh commented on lib/core/presentation/widgets/poap/poap_transfer_success_poup/poap_transfer_success_popup.dart
> +                    Align(
👍

2023-09-15 08:27 UTC, mthinh commented on lib/core/presentation/widgets/poap/poap_transfer_popup/poap_transfer_popup.dart
> +  }
it's a popup, i think we wont need to use auto router

2023-09-15 08:27 UTC, mthinh commented
@roncoderpush @sieuhuflit comment fixed, please help recheck

2023-09-15 09:24 UTC, sieuhuflit approved these changes
Look good, nice work 👍

2023-09-15 09:25 UTC, merged