feat: attached virtual and location to event creation flow
lemonadesocial/lemonade-flutter pull request #316
Opened 2023-12-21 05:14 UTC by sieuhuflit

## Overview
- Provide edit virtual when create event
- Can attached location into event creation flow

## Demo

![Dec-21-2023 12-06-59](https://github.com/lemonadesocial/lemonade-flutter/assets/7247063/01deb85b-3fb9-4ca2-ba87-d889a56ed565)

2023-12-21 05:55 UTC, mthinh commented on lib/core/application/event/create_event_bloc/create_event_bloc.dart
> +        timezone: "Asia/Bangkok",
why timezone is hardcoded ?

2023-12-25 08:57 UTC, sieuhuflit commented on lib/core/application/event/create_event_bloc/create_event_bloc.dart
> +        timezone: "Asia/Bangkok",
Resolved

2023-12-25 08:57 UTC, sieuhuflit commented
Please help review again 🙏 @mthinh

2023-12-27 02:49 UTC, mthinh commented
flutter_native_timezone is outdated, 2 years no maintained, please try another package which is well maintained. 
Suggest https://pub.dev/packages/flutter_timezone

2023-12-27 02:50 UTC, mthinh requested changes
Leave one change request

2023-12-27 03:09 UTC, sieuhuflit commented
> flutter_native_timezone is outdated, 2 years no maintained, please try another package which is well maintained. Suggest https://pub.dev/packages/flutter_timezone

holy, I'm aware about this, but I install the wrong package 😆

2023-12-27 03:13 UTC, sieuhuflit commented
Resolved @mthinh please help re-check

2023-12-27 05:50 UTC, mthinh approved these changes

2023-12-27 08:31 UTC, merged